# Generated by Django 5.1.5 on 2025-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='default_reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_rest',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_sets',
            field=models.IntegerField(default=3),
        ),
    ]
