# Generated by Django 5.1.5 on 2025-02-03 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_exercise_default_reps_exercise_default_rest_and_more'),
        ('pwp', '0002_fitnessgoal_weighttracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_sets', models.IntegerField(default=3)),
                ('planned_reps', models.IntegerField(default=10)),
                ('actual_sets', models.IntegerField(blank=True, null=True)),
                ('actual_reps', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.exercise')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='pwp.workoutsession')),
            ],
        ),
    ]
